#!/bin/sh
# demon script of SoftEther VPN Server 
# reference:
#   https://www.digitalocean.com/community/tutorials/how-to-setup-a-multi-protocol-vpn-server-using-softether

DAEMON=/opt/vpnserver/vpnserver
LOCK=/var/lock/subsys/vpnserver

test -x $DAEMON || exit 0
case "$1" in
    start)
        $DAEMON start
        touch $LOCK
    ;;

    stop)
        $DAEMON stop
        rm $LOCK
    ;;

    restart)
        $DAEMON stop
        sleep 3
        $DAEMON start
    ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
